### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by boonejeeper** [elevow/table#1]
We need a random number generator to serve as a util.  

Determine necessity of using a library.

Functions
randomInt(max) // 0 <= number < max
randomInt(min, max) // min <= number <= max

**Comment by boonejeeper** [comment]
Point in favor of not using a library: We will not need much of the library.

**Comment by elevow** [comment]
I made max the first value in the function. That way if min is undefined then we use 0.

**Comment by boonejeeper** [comment]
pull request #5 completes issue
